spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1122
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
post:
  image:
    path: upload
application:
  jwt:
    secrete: aivrOF9QScLe8PHPijLAkgBlaucl0SxeTnYQGHo5IQln40PwdNYLBoz80XUk5Owd
    expiration: 43200000